#environment: &buildenv/
#  GOMODCACHE: /root/project/gomodcache 

version: 2.1
jobs: 
  test:
    machine:
      image: ubuntu-2004:202010-01
    # docker:
    #   - image: golang:1.18  # 使用您需要的 Go 版本的 Docker 镜像
#    parallelism: 3
    steps:
      # - run: sadfasdf
      - checkout  # 检出代码仓库
      # - setup_remote_docker:
      #     version: 20.10.14
      #     docker_layer_caching: true

      - run: docker run -d --name redis -p 6379:6379 redis
      # - run: docker ps -a
      # - run: sudo apt update && sudo apt install net-tools
      - run: netstat -tunlp
      # - run: watch date

#      - run:
#          name: Run Tests
#          command: go test ./bufferpool/...
      # - run: ls -l 
      # - run: go mod download -x
#      - run:
#          go test   -timeout  30m -v -cover  -run="^Test.*" -coverpkg=./... ./...
#          -coverprofile=/tmp/coverage.out
#      - run: go tool cover -html=/tmp/coverage.out -o /tmp/coverage.html
#      - store_artifacts:
#          path: /tmp/coverage.html
#          destination: artifact-file
#      - run: go test ./cache/...
      # - run: go test ./parser/...
      # # - run: go test ./watcher/...
      # - run: go test ./commands/...
      # - run: go test ./config/...
#      - run: go test ./hugolib/...

workflows:
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - circleci  # 指定只在 main 分支上运行
