#environment: &buildenv/
#  GOMODCACHE: /root/project/gomodcache 

version: 2.1
jobs: 
  test:
    docker:
      - image: golang:1.18  # 使用您需要的 Go 版本的 Docker 镜像
#    parallelism: 3
    steps:
      - checkout  # 检出代码仓库
#      - run:
#          name: Run Tests
#          command: go test ./bufferpool/...
      - run: go mod download -x
#      - run:
#          go test   -timeout  30m -v -cover  -run="^Test.*" -coverpkg=./... ./...
#          -coverprofile=/tmp/coverage.out
#      - run: go tool cover -html=/tmp/coverage.out -o /tmp/coverage.html
#      - store_artifacts:
#          path: /tmp/coverage.html
#          destination: artifact-file
#      - run: go test ./cache/...
      - run: go test ./parser/...
      - run: go test ./watcher/...
#      - run: go test ./commands/...
#      - run: go test ./config/...
#      - run: go test ./hugolib/...

workflows:
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - circleci  # 指定只在 main 分支上运行
